In [18]:
path = '/Volumes/Seagate/ML/Machine-Learning-Implementations/ML'
import sys
sys.path.insert(1, path)
path = '/Volumes/Seagate/ML/Machine-Learning-Implementations'
import sys
sys.path.insert(1, path)

import numpy as np 
import pandas as pd

In [19]:
#generate data
x1 = np.random.normal(0,1,1000)
x2 = np.random.uniform(0,1,1000)
x3 = np.random.gamma(2,12,1000)

X = np.array([x1,x2,x3]).T

alpha = np.random.uniform()
beta = np.random.uniform(0,1,3)
Y = alpha+(np.dot(X,beta))

print(alpha)
print(beta)

0.03795975917737371
[0.09853408 0.68772374 0.88846098]


In [20]:
from sklearn import linear_model
lr = linear_model.LinearRegression()
lr.fit(X,Y)
print(np.isclose(lr.predict(X),Y).all())

print(lr.intercept_)
print(lr.coef_)

True
0.03795975917737593
[0.09853408 0.68772374 0.88846098]


In [24]:
from ML import LinearRegression as lr_ml
lr = lr_ml()
lr.fit(X,Y)

print(lr.weights)

[0.03795976 0.09853408 0.68772374 0.88846098]


In [25]:
from ML import gradientDescent as gd
optimiser = gd(0.001)
lr = lr_ml(method = optimiser)
lr.fit(X,Y)

train loss: 0.202513: 100%|██████████| 100/100 [01:21<00:00,  1.22it/s]


In [26]:
lr.weights

array([0.88261657, 0.50696696, 0.72976508, 0.86544187])

In [27]:
lr.loss(lr.weights)

0.20025692934448716