In [5]:
path = '/Volumes/Seagate/MLImplementations/'
path = '/Volumes/Seagate/MLImplementations/ML'
import sys
sys.path.insert(1, path)

In [8]:
import ML
import numpy as np 
import pandas as pd

In [34]:
#generate data
x1 = np.random.normal(0,1,1000)
x2 = np.random.uniform(0,1,1000)
x3 = np.random.gamma(2,12,1000)

X = np.array([x1,x2,x3]).T

alpha = np.random.uniform()
beta = np.random.uniform(0,1,3)

Y = (alpha + beta*X).sum(1)

print(alpha)
print(beta)

0.7417021000127564
[0.4452385  0.67999105 0.67150768]


In [38]:
from sklearn import linear_model
lr = linear_model.LinearRegression()
lr.fit(X,Y)
print(np.isclose(lr.predict(X),Y).all())

print(lr.intercept_)
print(lr.coef_)

True
2.22510630003827
[0.4452385  0.67999105 0.67150768]


In [48]:
from ML import LinearRegression as LR
lr = LR()
lr.setUp(X,Y)
result = lr.fit(optimiser = 'OLS')
print(np.isclose(lr.predict(X), Y).all())
print(result[0])
print(result[1:])

True
2.225106300038277
[0.4452385  0.67999105 0.67150768]


In [54]:
from ML import gradientDescent as gd
lr = LR()
lr.setUp(X,Y)
op = gd(0.001, lr)
lr.fit(op)

Progress on iteration 0.0%current cost 1.5964673585652736
Progress on iteration 20.0%current cost 0.001374468905840029
Progress on iteration 24.5% 
iteration stopped due to tolerance difference reached


array([2.14443738, 0.44591713, 0.80896927, 0.6720167 ])